//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlchemyAPIClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AlchemyAPIClientResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlchemyAPIClientResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlchemyAPIClient.AlchemyAPIClientResources", typeof(AlchemyAPIClientResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve content for analysis.
        /// </summary>
        internal static string cannot_retrieve_error {
            get {
                return ResourceManager.GetString("cannot_retrieve_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your API key is invalid please check on www.alchemyapi.com.
        /// </summary>
        internal static string invalid_key_error {
            get {
                return ResourceManager.GetString("invalid_key_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is not html content.
        /// </summary>
        internal static string page_not_html_error {
            get {
                return ResourceManager.GetString("page_not_html_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This language is not supported for this service call.
        /// </summary>
        internal static string unsupported_language_error {
            get {
                return ResourceManager.GetString("unsupported_language_error", resourceCulture);
            }
        }
    }
}
